DROP DATABASE chat;
CREATE DATABASE IF NOT EXISTS chat;
USE chat;
DROP TABLE IF EXISTS message;
CREATE TABLE IF NOT EXISTS message (
  id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  alias CHAR(32) NOT NULL,
  room VARCHAR(256) NOT NULL,
  text VARCHAR(512) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
