DROP TABLE IF EXISTS message;
CREATE TABLE IF NOT EXISTS message (
  id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  alias CHAR(32) NOT NULL,
  room VARCHAR(256) NOT NULL,
  text VARCHAR(512) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id)
);
